### PR TITLE
Decorator Execution Order

### LINKED ISSUE #23: Decorator Execution Order
## Code Example

https://github.com/fabioformosa/typegoose-validation-error/tree/typegoosev6

## Do you know *why* it happenes?

Decorator Execution order
1. method & property decorators
2. class decorators

this conflicts because of:
1. @prop (property decorator) needs `name` of schema, which is applied in @modelOptions (class decorator)

### PR DESCRIPTION
**Pull request by hasezoey**
Tried to fix the Decorator Execution Order problem (#23) 

- cache @prop (@arrayProp @mapProp) to be executed when _buildSchema is called
- disable _id test in biguser
- fix tests for some thing
- outsource uniqueID creation to "utils.createUniqueID"
- add doc note to use the right execution order for something like hooks

Known Issues:
- none known issues anymore, verification needed

This PR might be breaking something (but shouldnt be too much and work like v5)

PS: 
- related mongoose issue https://github.com/Automattic/mongoose/issues/8137
- before this pr, subdocuments wouldn't build parent's properties into its own, because of the call directly to `_buildSchema` but changing it back, dosnt work for _id too

fixes #23

### CODE REVIEW

**Comment by hasezoey** [comment]
@B-Stefan could you test 13069fbff3b28ce8f1a9935bbc41bb622308cd27 with your pr? (#21)

@fabioformosa could you test it with your (public & private) repos? (13069fbff3b28ce8f1a9935bbc41bb622308cd27)

**Comment by fabioformosa** [comment]
> @fabioformosa could you test it with your (public & private) repos? ([13069fb](https://github.com/hasezoey/typegoose/commit/13069fbff3b28ce8f1a9935bbc41bb622308cd27))

I'm just testing. I built source code of branch `r6/cache-inner-class-decorators` and I pushed the package in my own nexus.
In my project the fields of nested model are unsaved. I'm looking for reproducing the problem in the sample project with foo and bar. I let you know...

**Comment by hasezoey** [comment]
> In my project the fields of nested model are unsaved.

thanks for letting me know, just wanted to test something, and like i said in the commits, i dont trust the tests in this one
just tried to wrap an `buildSchema` into an `new Schema(buildSchema, _id: false)` (pseudo)

**Comment by hasezoey** [comment]
@fabioformosa the commit with the test got reverted

implemented a "workaround" for now, but it only works, if you dont use the same class / schema for `Ref` or directly
example
`@prop({ _id: false })` dosnt do "anything" anymore, and `@modelOptions({ schemaOptions: { _id: false } })` should be used now

but the clear drawbacks are:
- the model where the `@modelOptions` is applied, cant be used for Ref's & directly

**Comment by hasezoey** [comment]
Found a fix (/ knew about, but didnt wanted to use it) for the _id problem

need to disable buildSchema caching & add optional schema options to buildSchema (that gets passed to `_buildSchema`)

**Comment by hasezoey** [comment]
I dont understand why the tests `should error if no valid type is supplied to "@mapProp" [InvalidTypeError]` sometimes fails, and sometimes not in travis, and only in the test "Travis CI - Branch", "Travis CI - Pull Request" passes always...

**Comment by hasezoey** [comment]
@fabioformosa tested with your verification repo, after renaming one of the bar classes, the two tests pass, because for now, same name is not supported, could you test with a "more advanced" / "real world" project?

**Comment by fabioformosa** [comment]
> @fabioformosa tested with your verification repo, after renaming one of the bar classes, the two tests pass, because for now, same name is not supported, could you test with a "more advanced" / "real world" project?

I don't understand, have you disabled the chance to use more classes with the same name? why?
I would use this feature, at the momento also with known issues (`_id:false` doesn't work on `@prop`).

**Comment by hasezoey** [comment]
@fabioformosa since ac4964a2e904cfd6eba625d925a5bda65c9f4a26, but this was only in the r6/master branch, forgot to re-enable it again / wanted to have the actual issue fixed first, then i could tackle that

**Comment by hasezoey** [comment]
@fabioformosa does 0c13a06173d65e144cedb8dda19fb619cc4abef3 what you want it to do?

**Comment by fabioformosa** [comment]
Ok, I confirm that in verification repo this feature branch works with more classes with same name.
In the next 2 days, I'll try to use this feature branch version in a bigger project.
I'll let you know. 
Thank you.

**Comment by fabioformosa** [comment]
Ok @hasezoey, I've tested, it's OK for me. Also `_id: false` works now.

**Comment by hasezoey** [comment]
@fabioformosa did you notice any slowdowns? i just ask because of the removal of caching some things

**Comment by fabioformosa** [comment]
> @fabioformosa did you notice any slowdowns? i just ask because of the removal of caching some things

At the application startup or during save/find operations?

**Comment by hasezoey** [comment]
> At the application startup or during save/find operations?

in general, but mainly startup / when you make the models / schemas

**Comment by fabioformosa** [comment]
I have not so much models to notice slowdowns. For me it's OK, at the moment.

**Comment by hasezoey** [comment]
Squash Merged in ada5cfb81798137aebb02dc68159d93809f3f828

<sub>Github dosnt let me mark this as "merged"...</sub>

**Pull request closed without merging**
